[databases]
[databases.production]
name = "mydb"
host = "localhost"
port = 3306
username = "root"
password = "root123"

[databases.test]
name = "testdb"
host = "localhost"
port = 3306
username = "root"
password = "root123"
ss = ["1", "2", "3"]
